version: '3'
services:

  redis:
    image: "redis:7.2.2-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes  # Enables AOF persistence

  # backend:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.backend
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - redis

  # frontend:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  redis-data:
