FROM node:21-alpine3.18

WORKDIR /app

# Copy package.json and package-lock.json
COPY ./frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the frontend code
COPY ./frontend .

# Expose the correct port used by Vite (default: 5173)
EXPOSE 5173

# Start the development server
CMD ["npm", "run", "dev"]
