FROM node:21-alpine3.18 AS build
WORKDIR /app

COPY ./frontend/package*.json ./

RUN npm install

COPY ./frontend .

RUN npm run build

FROM node:21-alpine3.18
WORKDIR /app

COPY --from=build /app/package*.json ./
COPY --from=build /app/build ./build

RUN npm install --production

EXPOSE 3000

CMD ["npm", "start"]