FROM node:21-alpine3.18 AS build
WORKDIR /app

COPY ./frontend/package*.json ./

RUN rm -rf node_modules
RUN rm -rf build

RUN npm install
COPY ./frontend .
RUN npm run build

FROM node:21-alpine3.18 AS run
WORKDIR /app

COPY --from=build /app/package*.json ./
COPY --from=build /app/build ./build

RUN npm install --production

EXPOSE 3000

ENTRYPOINT [ "node", "build" ]
