version: "3"
services:
  redis:
    image: "redis:7.2.2-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes # Enables AOF persistence

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
      - "2345:2345" # Delve debugger port
    volumes:
      - ./backend:/app
      - ./backend/.air.toml:/app/.air.toml
    depends_on:
      - redis
    # command: ["dlv", "debug", "--headless", "--listen=:2345", "--api-version=2", "--accept-multiclient"]


  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  redis-data:
